### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by innawe** [NoahCardoza/python-requests-anonymous-session#2]
Hello, i try this module with no success, it gives me this error:

`Traceback (most recent call last):
  File "x.py", line 1, in <module>
    from python_requests_anonymous_session import AnonymousSession
ImportError: cannot import name 'AnonymousSession' from 'python_requests_anonymous_session' (/Users/phil/Library/Python/3.7/lib/python/site-packages/python_requests_anonymous_session/__init__.py)`

The code i try is this:

`from python_requests_anonymous_session import AnonymousSession
 
 session = AnonymousSession(browser={
    'custom': 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) 
 Mobile/15E148',
 })
 r = session.get("https://www.google.com/")
 print(r.text, r.status_code)`

Thanks again for this module!

**Comment by NoahCardoza** [comment]
Sorry for the lag. Finally had time to take a look and upload a working version to PyPi.
